### ISSUE TITLE
E/DfuImpl: Device returned error after sending file (error 6): OPERATION FAILED

### ISSUE THREAD

**Issue by zhouzhijin0908** [NordicSemiconductor/Android-DFU-Library#109]
E/DfuImpl: Device returned error after sending file (error 6): OPERATION FAILED

what's means? why?

**Comment by philips77** [comment]
Hi,
If you're using the DFU bootloader from SDK 13, there may be many reasons for error 6.
All are caused by an invalid ZIP file with the firmware. It may be wrong signature, incorrect required SoftDevice ID, invalid app version  (must be >= to the current app verison), invalid bootloader version (if you update the bootloader (must be > then the current bl version).
Ensure that your ZIP is created correctly and is signed with correct private key (that matches the public key in the bootloader code), that it was created with --sd-id matching the current SD, etc.

**Comment by zhouzhijin0908** [comment]
Same bracelet, same upgrade firmware package;
Upgrade 100 times and have a 2% chance of this error on some phones.
But on some phones (sm-a320f, android7.0) there is a 60% chance of this error

**Comment by philips77** [comment]
Hmm... Could you post relevant log here? 
It may be caused by the device sending too quickly and flash saving is not fast enough, or some other reason. Did you try enabling PRNs on those devices with [this method](https://github.com/NordicSemiconductor/Android-DFU-Library/blob/release/dfu/src/main/java/no/nordicsemi/android/dfu/DfuServiceInitiator.java#L165)?

**Comment by philips77** [comment]
Hi, did you manage to solve your issue?

**Comment by philips77** [comment]
I'll close the issue due to inactivity. If you still face the problem, please open a new issue and give more details.

**Comment by feiyangjiayuan** [comment]
![image](https://user-images.githubusercontent.com/16984132/49994044-66035480-ffc3-11e8-9567-a62d029ee4cf.png)

**Comment by philips77** [comment]
Hi, what SDK is your DFU bootloader from?
