### ISSUE TITLE
Only Upload Application part

### ISSUE THREAD

**Issue by pyramid-ali** [NordicSemiconductor/Android-DFU-Library#123]
Hi,
when I upload my zip file that contains application and bootloader part only application part will be uploaded.
everything works correctly but I need to upload all parts. I don't know what is happening but when I use "NRF Toolbox" all parts will be uploaded.
when I set DfuProgressListener also I get 1 for totalParts property!
I'm using react native version but I checked android implementation and everything looks good and is same with "NRF Toolbox" implementation. only difference I can see is in setZip section;
in react-native version we pass only filePath but in nrf toolbox we pass uri + filepath.
is there any bug with setting null to uri?

**Comment by philips77** [comment]
No, path is actually kinda deprecated, as it may require storage permission, if the file is not in app's private folder. But there's no difference.
There are only 2 possible reasons for this behavior:
1. You set the scope to app only,
2. You set the type in the Intent to app, instead of auto, which actually is the same as 1., but not using initiator.
