### ISSUE TITLE
Are there breaking changes between 1.12.0 and 2.0.0

### ISSUE THREAD

**Issue by tentom** [NordicSemiconductor/Android-DFU-Library#351]
### Your question
I am currently using version 1.12.1 of the DFU library on Android, usually, a major version bump implies changes that are not backwards-compatible but I could not find any mentioned in the version history or in the documentation. Is it safe to assume that there are no issues with backwards compatibility between 1.12.0 and 2.0.0? If there are, what are they?

**Comment by philips77** [comment]
Hello,
No, there are no pretty much any changes. The jump 1.x -> 2.x wa made purely because of the new DFU application. Due to the fact, that now both lib and app release is done on `git tag`, the version name is the same, so sometimes we will have version bump with no changes in the lib. We try to document all changes in Releases. Have a look at: https://github.com/NordicSemiconductor/Android-DFU-Library/releases/tag/2.0.0
