### ISSUE TITLE
DfuServiceInitiator requires a new method 

### ISSUE THREAD

**Issue by xiaozhao1995** [NordicSemiconductor/Android-DFU-Library#444]
### Target

Library

### Describe the feature

```java
	/**
	 * Sets the time required by the device to reboot. The library will wait for this time to disconnect
	 * for the device to make sure device has received BLE_GATTC_EVT_HVX
	 *
	 * @param disconnectTime the disconnect time in milliseconds,default 0.
	 * @return the builder
	 */
	public DfuServiceInitiator setDisconnectTimeout(final long disconnectTime) {
		this.disconnectTime = disconnectTime;
		return this;
	}
```
We found that on some phones, such as Huawei mate30pro, Huawei pura70, if you call (`ButtonlessDfuImpl#performDfu`）disconnect immediately after receiving `0x200101`, the device may not receive the _BLE_GATTC_EVT_HVX_ event, resulting in an interrupt into boot.

**Comment by philips77** [comment]
Hello,
Sorry for teh very long delay. I had a lot on my plate. 

Usually, it's the device that initiates disconnection and the lib calls `disconnect()` so that it doesn't have to wait Supervision Timeout. Wouldn't it be sufficient to just wait ~100 ms before calling this method? What would be the value of `disconnectTime` that you'd intend to use?

Or did you fix your issue already in some other way?

**Comment by xiaozhao1995** [comment]
We currently have a delay of 500 milliseconds enabled. I'm not sure if this value is optimal, but it resolves the issues on all devices where problems have occurred.

**Comment by xiaozhao1995** [comment]
![WX20241025-162809](https://github.com/user-attachments/assets/a781c338-f04f-4c5c-98bb-9a90284b7763)

**Comment by philips77** [comment]
I'll add 500 ms delay in upcoming version 2.7.0.
